version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    container_name: portfolio-astro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Production optimizations
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security optimizations
    read_only: true
    tmpfs:
      - /tmp:size=10M
    security_opt:
      - no-new-privileges:true

  # Development service (optional)
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "4321:4321"
    container_name: portfolio-astro-dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    profiles:
      - dev
